import json,re,time
from pathlib import Path
from genlayer_py import create_account,create_client
from genlayer_py.chains import studionet

ROOT=Path(__file__).parents[1]; ENV=(ROOT.parents[3]/'accounts.env').read_text(encoding='utf-8'); ADDRESS='0x15ba04f276568e7735A701533fFd4972Ed71d09a'; COMMIT='84aa5358886af10823b11d1b734faaa810b65356'
def account(slot):
    key=re.search(rf'^ACCOUNT_{slot}_GENLAYER_PRIVATE_KEY\s*=\s*"?([^"\r\n]+)',ENV,re.M).group(1).strip();return create_account(account_private_key=key)
def send(client,name,args):
    tx=client.write_contract(address=ADDRESS,function_name=name,args=args,value=0);print(name+'='+str(tx),flush=True);receipt=client.wait_for_transaction_receipt(transaction_hash=tx,status='FINALIZED',retries=180,interval=5000,full_transaction=True);leader=(receipt.get('consensus_data',{}).get('leader_receipt') or [{}])[0];assert receipt.get('status_name')=='FINALIZED' and str(receipt.get('result_name')).upper()=='MAJORITY_AGREE' and str(leader.get('execution_result')).upper()=='SUCCESS',(name,receipt);return str(tx)
author,rerunner,auditor=account(1),account(2),account(3);author_client=create_client(chain=studionet,account=author);rerunner_client=create_client(chain=studionet,account=rerunner);auditor_client=create_client(chain=studionet,account=auditor);study_id='RN-LIVE-'+str(int(time.time()))
urls={'protocol':f'https://raw.githubusercontent.com/SAMiiNW/replication-notebook/{COMMIT}/docs/evidence/protocol.txt','original':'https://samiinw-replication-notebook.pages.dev/evidence/original-result.txt','reproduction':f'https://cdn.jsdelivr.net/gh/SAMiiNW/replication-notebook@{COMMIT}/docs/evidence/reproduction.txt','audit':f'https://github.com/SAMiiNW/replication-notebook/raw/{COMMIT}/docs/evidence/audit-rerun.txt'}
transactions={};transactions['open']=send(author_client,'open_study',[study_id,rerunner.address,auditor.address,'The deterministic recovery routine remains within five percent of the published median recovery time.','median recovery time',500,urls['protocol'],urls['original'],3600]);transactions['replicate']=send(rerunner_client,'submit_replication',[study_id,urls['reproduction']]);opened=author_client.read_contract(address=ADDRESS,function_name='get_study',args=[study_id]);assert opened['state']=='CHALLENGE_OPEN',opened;transactions['audit']=send(auditor_client,'challenge_replication',[study_id,urls['audit']]);final=author_client.read_contract(address=ADDRESS,function_name='get_study',args=[study_id]);assert final['state']=='FINAL' and final['final_outcome']=='REPRODUCED',final;print(json.dumps({'studyId':study_id,'state':final['state'],'outcome':final['final_outcome'],'originalValue':final['original_value'],'reproductionValue':final['reproduction_value'],'challengeValue':final['challenge_value'],'transactions':transactions},default=str),flush=True)
